/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentIdRouteImport } from './routes/$documentId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiDocumentsRequestRouteImport } from './routes/api/documents/request'
import { Route as ApiDocumentsDocumentIdRouteImport } from './routes/api/documents/$documentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDocumentsDocumentIdRefuteRouteImport } from './routes/api/documents/$documentId/refute'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentIdRoute = DocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRequestRoute = ApiDocumentsRequestRouteImport.update({
  id: '/api/documents/request',
  path: '/api/documents/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsDocumentIdRoute = ApiDocumentsDocumentIdRouteImport.update({
  id: '/api/documents/$documentId',
  path: '/api/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsDocumentIdRefuteRoute =
  ApiDocumentsDocumentIdRefuteRouteImport.update({
    id: '/refute',
    path: '/refute',
    getParentRoute: () => ApiDocumentsDocumentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$documentId': typeof DocumentIdRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/search': typeof ApiSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$documentId': typeof ApiDocumentsDocumentIdRouteWithChildren
  '/api/documents/request': typeof ApiDocumentsRequestRoute
  '/api/documents/$documentId/refute': typeof ApiDocumentsDocumentIdRefuteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$documentId': typeof DocumentIdRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/search': typeof ApiSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$documentId': typeof ApiDocumentsDocumentIdRouteWithChildren
  '/api/documents/request': typeof ApiDocumentsRequestRoute
  '/api/documents/$documentId/refute': typeof ApiDocumentsDocumentIdRefuteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$documentId': typeof DocumentIdRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/search': typeof ApiSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$documentId': typeof ApiDocumentsDocumentIdRouteWithChildren
  '/api/documents/request': typeof ApiDocumentsRequestRoute
  '/api/documents/$documentId/refute': typeof ApiDocumentsDocumentIdRefuteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$documentId'
    | '/login'
    | '/search'
    | '/signup'
    | '/api/inngest'
    | '/api/search'
    | '/api/auth/$'
    | '/api/documents/$documentId'
    | '/api/documents/request'
    | '/api/documents/$documentId/refute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$documentId'
    | '/login'
    | '/search'
    | '/signup'
    | '/api/inngest'
    | '/api/search'
    | '/api/auth/$'
    | '/api/documents/$documentId'
    | '/api/documents/request'
    | '/api/documents/$documentId/refute'
  id:
    | '__root__'
    | '/'
    | '/$documentId'
    | '/login'
    | '/search'
    | '/signup'
    | '/api/inngest'
    | '/api/search'
    | '/api/auth/$'
    | '/api/documents/$documentId'
    | '/api/documents/request'
    | '/api/documents/$documentId/refute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentIdRoute: typeof DocumentIdRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsDocumentIdRoute: typeof ApiDocumentsDocumentIdRouteWithChildren
  ApiDocumentsRequestRoute: typeof ApiDocumentsRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$documentId': {
      id: '/$documentId'
      path: '/$documentId'
      fullPath: '/$documentId'
      preLoaderRoute: typeof DocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/request': {
      id: '/api/documents/request'
      path: '/api/documents/request'
      fullPath: '/api/documents/request'
      preLoaderRoute: typeof ApiDocumentsRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$documentId': {
      id: '/api/documents/$documentId'
      path: '/api/documents/$documentId'
      fullPath: '/api/documents/$documentId'
      preLoaderRoute: typeof ApiDocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$documentId/refute': {
      id: '/api/documents/$documentId/refute'
      path: '/refute'
      fullPath: '/api/documents/$documentId/refute'
      preLoaderRoute: typeof ApiDocumentsDocumentIdRefuteRouteImport
      parentRoute: typeof ApiDocumentsDocumentIdRoute
    }
  }
}

interface ApiDocumentsDocumentIdRouteChildren {
  ApiDocumentsDocumentIdRefuteRoute: typeof ApiDocumentsDocumentIdRefuteRoute
}

const ApiDocumentsDocumentIdRouteChildren: ApiDocumentsDocumentIdRouteChildren =
  {
    ApiDocumentsDocumentIdRefuteRoute: ApiDocumentsDocumentIdRefuteRoute,
  }

const ApiDocumentsDocumentIdRouteWithChildren =
  ApiDocumentsDocumentIdRoute._addFileChildren(
    ApiDocumentsDocumentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentIdRoute: DocumentIdRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsDocumentIdRoute: ApiDocumentsDocumentIdRouteWithChildren,
  ApiDocumentsRequestRoute: ApiDocumentsRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
